added unicode escaping
keli5/kcsh pull request #28
Opened 2024-04-13 02:05 UTC by sadanslargehole

Unicode escaping now works in config theme files!! 

use `\uxxxx` to use a Unicode value

2024-05-13 18:00 UTC, keli5 commented
Doesn't work with extended Unicode e.g. \u1f386 as a prompt character makes the character come out "I6"

2024-05-13 18:00 UTC, keli5 requested changes
see comment

2024-05-14 18:11 UTC, sadan4 reviewed
fixed

2024-05-14 18:15 UTC, keli5 requested changes

2024-05-14 18:15 UTC, keli5 commented on shellutil/settingsutil.hpp
> +        } else if (input[i] == '\\' && input[i + 1] == 'U') {
Could this if statement be merged with the one above? Something like `input[i] == '\\' && (input[i + 1] == 'U' || input[i + 1] == 'u')`

2024-05-14 18:18 UTC, sadan4 commented on shellutil/settingsutil.hpp
> +        } else if (input[i] == '\\' && input[i + 1] == 'U') {
each uses a different number of characters, they could but then you would have to do something like `\u001234` for a four digit unicode character

your choice

2024-05-14 18:21 UTC, keli5 commented on shellutil/settingsutil.hpp
> +        } else if (input[i] == '\\' && input[i + 1] == 'U') {
I figured that's what you were supposed to do anyways based on the last commit message, think it would make more sense and be simpler code to do it that way

2024-05-16 17:40 UTC, sadan4 commented on shellutil/settingsutil.hpp
> +        } else if (input[i] == '\\' && input[i + 1] == 'U') {
done

2024-05-17 23:29 UTC, keli5 commented
probably looks good

2024-05-17 23:29 UTC, merged